---
AllCops:
  Exclude:
    - "vendor/**/*"

Metrics/MethodLength:
  CountComments: false
  Max: 15

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - spec/**/*_spec.rb
