common: &common
  octokit:
    token: YOUR_GITHUB_TOKEN
  lita:
    robot:
      name: dude
      log_level: :info
      adapter: :shell

development:
  <<: *common

test:
  <<: *common
  lita:
    robot:
      name: test
